### ISSUE TITLE
Add ngx_http_stub_status_module

### ISSUE THREAD

**Issue by rakshazi** [wunderkraut/alpine-nginx-pagespeed#10]
Hello!
Please, add `ngx_http_stub_status_module` to Dockerfile:

```
--with-http_stub_status_module
```

**Comment by iler** [comment]
Hi!

Thanks for the feedback! I wonder why we have forgotten this. I will make a PR for this. In the future you can also make PR's as we are happy to get more contributors :)

**Comment by rakshazi** [comment]
Thank you very much!
Ok, I will create PR next time :smile:

**Comment by aleksijohansson** [comment]
Fixed in #11

**Comment by aleksijohansson** [comment]
Available in tags latest, v1.11, v1.11.5 and v1.11.5-1 after the build finishes here https://quay.io/repository/wunder/alpine-nginx-pagespeed
