### ISSUE TITLE
Point logs to somewhere Docker can read

### ISSUE THREAD

**Issue by aleksijohansson** [wunderkraut/alpine-nginx-pagespeed#14]

**Comment by onnimonni** [comment]
I think this is already resolved?

Seems to me that these lines in the `Dockerfile` are sufficient: https://github.com/wunderkraut/image-fuzzy-alpine-nginx-pagespeed/blob/master/Dockerfile#L123-L125

Did you want to save the logs into a file inside the container instead?

**Comment by aleksijohansson** [comment]
@onnimonni You are correct, stdout and stderr should be sufficient.
