### ISSUE TITLE
./configure: error: invalid option "--with-http_map_module"

### ISSUE THREAD

**Issue by james-nesbitt** [wunderkraut/alpine-nginx-pagespeed#5]
it is a default core module: https://github.com/nginx/nginx/blob/531e6fbfd6c785a7b42c285c12d3f0721cc989c7/auto/options

**Comment by iler** [comment]
This fixes it https://github.com/wunderkraut/alpine-nginx-pagespeed/commit/1c6917425d59bbfd7b3b2306118dc454ff3d57a1
